name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Change Dir
      run: cd src
    - name: Install dependencies
      run: dotnet restore src/go2cs.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src/go2cs/go2cs.csproj
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      with: 
        name: dist
        path: dist
